config/routes.rb
Movies::Application.routes.draw do
  devise_for :users
  resources :movies do
    get 'toggle_watch', :on => :member
    get 'toggle_want', :on => :member    
    get 'toggle_tag', :on => :member
    get 'toggle_rob', :on => :member
    get 'toggle_marina', :on => :member
    get 'all', :on => :collection
    get 'tagged', :on => :collection
    get 'unwatched', :on => :collection    
    get 'watched', :on => :collection
    get 'wanted', :on => :collection
    get 'recent_watched', :on => :collection
    get 'recent_added', :on => :collection    
    get 'rob', :on => :collection
    get 'marina', :on => :collection
    get 'id_list', :on => :collection
    get 'user_queue', :on => :collection
    get 'set_user_queue', :on => :collection
    get 'search', :on => :collection
  end
  
  root to: 'movies#index'
  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :delete, :edit, :toggle_watch, :toggle_tag, :toggle_want, :toggle_rob, :toggle_marina]
  # GET /movies
  # GET /movies.json
  
  
  def render_index movies, show_wanted = false, show_rob = true, show_marina = true, show_tagged = true, show_watched = true
    @show_wanted = show_wanted
    @show_rob = show_rob
    @show_marina = show_marina
    @show_tagged = show_tagged
    @show_watched = show_watched  
    respond_to do |format|

      format.html { render :index }
      format.json { render json: @movies }
    end
  end
  
  def index    
    if signed_in?
      redirect_to action: 'tagged'    
    else
      redirect_to action: 'rob'
    end
  end
  
  def search
    @title = "Search Results"
    if (!params.has_key?(:search))
      redirect_to action: 'index'
    end
    
    query_string = params[:search]
    @movies = Movie.where('name like ? or description like ?', "%#{query_string}%", "%#{query_string}%")
    render_index @movies, false, false, false
  end
  
  def unwatched
    @title = "Unwatched"
    #@movies = Movie.where(:watched => false, :wanted => false, :tagged => false)
    @movies = Movie.where(:watched => false)
    
    render_index @movies, false, false, false
  end  
  
  def all
    @title = "All"
    #@movies = Movie.where(:wanted => false)
    @movies = Movie.all
    render_index @movies    
  end
   
  def watched
    @title = "Watched"
    @movies = Movie.where(:watched => true)    
    render_index @movies 
  end
  
  def recent_watched
    @title = "Recently Watched"
    months_from = 1
    if (params.has_key?(:months_from))
      months_from = params[:months_from].to_i
    end
    
    months_to = months_from - 1
    
    if (params.has_key?(:months_to))
      months_to = params[:months_to].to_i
    end
    
    @movies = Movie.where(:watched => true, :watched_at =>  (Time.now.midnight - months_from.month..Time.now.midnight - months_to.month + 1.day)) 
    render_index @movies 
  end
  
  def recent_added
    @title = "Recently Added"
    @movies = Movie.where(:created_at => (Time.now.midnight - 45.day..Time.now + 1.day)) 
    render_index @movies 
  end   
  
 def tagged
    @title = "Tagged"
    #@movies = Movie.where(:tagged => true, :watched => false, :wanted => false)
    user_id = 1
    if (!current_user.nil?)
      user_id = current_user.id
    end
    @movies = get_collection({ :user_id => user_id }, 4) #handle for rob/marina independently
    render_index @movies, false, false, false
  end  
  
  def wanted
    @title = "Wanted"
    user_id = 1
    if (!current_user.nil?)
      user_id = current_user.id
    end
    #@movies = Movie.where(:wanted => true)    
    @movies = get_collection({ :user_id => user_id }, 5) #handle for rob/marina independently
    render_index @movies, true, false, false, false, false 
  end
  
  def rob
    @title = "Rob's Favorite"
    #@movies = Movie.where(:rob_favorite => true)    
    @movies = get_collection({ :user_id => 1 }, 1)
    render_index @movies, false, true, false, true, false 
  end        

  def marina
    @title = "Marina's Favorite"
    #@movies = Movie.where(:marina_favorite => true)  
    @movies = get_collection({ :user_id => 2 }, 1)    
    render_index @movies, false, false, true, true, false 
  end  
  
  def id_list
    @title = "Selected"
    if (params.has_key?(:id))
      movie_ids = params[:id].split(",").map { |s| s.to_i }     
    else
      movie_ids = params[:ids]
    end
    @movies = Movie.find_all_by_id(movie_ids)
    render_index @movies 
  end    
  
  def set_user_queue  
    set_collection 2  
  end  
  
  def user_queue
    @title = "User Picks"
    show_collection params, 2
  end  
  
  def set_collection movie_queue_type_id
    if !signed_in?
      return
    end
    user_id = current_user.id  
    movie_ids = params[:id].split(",").map { |s| s.to_i }
    user = current_user
    movies = Movie.find_all_by_id(movie_ids)    
    
    set_collection_impl user, movies, movie_queue_type_id
    
    movie_queues = get_movie_collections(user, movie_queue_type_id)
  end
  
  def set_collection_impl user, movies, movie_queue_type_id
  
    movie_queues = get_movie_collections(user, movie_queue_type_id)
    
    if (movie_queues.nil?)
      mc = MovieCollection.new
      mc.user_id = user_id
      mc.name = "Default"
      mc.collection_type_id = movie_queue_type_id
      user.movie_collections.push(mc)    
      movie_queues = get_movie_collections(user, movie_queue_type_id)
    else    
      movie_queues[0].movies.clear
    end
       
    movie_queues[0].movies.push(movies)
  end
  
  def get_collection params, movie_queue_type_id    
    found_picks = false
    movies = nil
    if (params.has_key?(:user_id))
      user_id = params[:user_id]
      user = User.find(user_id)
    else
      user = current_user
    end

    if (user.nil?)
      redirect_to action: 'index'
    end
    
    movie_queues = get_movie_collections(user, movie_queue_type_id)
    
    if (movie_queues.length >= 1)                 
      movies = movie_queues[0].movies
    end       
    
    movies
  end
  
  def show_collection params, movie_queue_type_id
  
    @movies = get_collection params, movie_queue_type_id
    
    if (!@movies.nil?)                   
      render_index @movies
    else
      redirect_to action: 'index'
    end  
  end
    
  def get_movie_collections user, collection_type_id
    if (user.nil?)
      return nil
    end
    
    movie_queues = user.movie_collections.where(:collection_type_id => collection_type_id)
    movie_queues  
  end
  

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end
    

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])
    #@movie = Movie.create(movie_params)
    
    @movie.update_tmdb
    movies = [@movie]
    set_collection_impl current_user, movies, 5 #set wanted    

    respond_to do |format|
      if !@movie.tmdb_id.nil? and @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])    

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def toggle_watch
    @movie = Movie.find(params[:id])
    @movie = @movie.toggle(:watched)
    
    if @movie.watched
      @movie.watched_at = Time.now
    else
      @movie.watched_at = nil
    end    
    
    @movie.save
    respond_to do |f|
      f.js
    end
  end
  
  
 def toggle_want
    toggle_collection current_user, 5, false
    
    @movie = Movie.find(params[:id])
    
    #TODO: auto-tag when toggling want?
    if !@movie.is_wanted current_user
      toggle_collection current_user, 4, false
    end
    
    respond_to do |f|
        f.js
    end    
    
  end
  
  def toggle_tag   
    toggle_collection current_user, 4, true
  end    
  
  def toggle_rob
    user = User.find(1)
    toggle_favorite user
  end 
  
  def toggle_marina
    user = User.find(2)
    toggle_favorite user
  end  

  def toggle_favorite user
    toggle_collection user, 1  
  end
  
  def toggle_collection user, collection_type_id, respond_false = false
    @movie = Movie.find(params[:id])
    movie_id = params[:id]
    
    movie_collections = get_movie_collections(user, collection_type_id)
    favorite_movies = movie_collections[0].movies
    movie_exists = favorite_movies.where(:id => movie_id).length == 1
    if (movie_exists)
      favorite_movies.delete(@movie)
    else
      favorite_movies.push(@movie)
    end
    
    if (respond_false.nil?)
      respond_to do |f|
        f.js
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    #def movie_params
      #params.require(:movie).permit(:description, :name, :rating, :tmdb_id, :year, :imdb_db, :poster_path, :watched, :wanted, :tagged)
    #end  
end

app/helpers/movies_helper.rb
module MoviesHelper  
  
  #This was used to seed the database with dumps of file trees of existing movies
  #You could modify the movie parsing and use it. It's reading in a "Movie Title (YEAR).ext" format.
  def self.add_movies file_path, watched
    File.open(file_path, "r").each_line do |line|
      title = line[0...-13]
      movie = Movie.new()
      movie.name = title
      movie.update_by_name
      movie.watched = watched
      begin
        movie.save
      rescue
        puts "fail" + line
      end
    end
  end   
  
  
  #This method is used to refresh data from themoviedb
  def self.update_all_movies
    movies = Movie.all
    movies.each do | m |
      if m.runtime.nil?
        mov = TmdbMovie.find(:id => m.tmdb_id)
        m.update_by_tmdb_obj mov     
        #m.update_by_name      
        #m.watched = true
        begin
          m.save
        rescue
          put "failed to save"
        end
      end
    end
  end
  
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tmdb_id %><br />
    <%= f.number_field :tmdb_id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1><%= @title %> Movies</h1>

<div id ="index_filters">
          <% if signed_in? %>
            <% if current_user.id == 1 %>
               <%= link_to 'Marina Queue', :controller => 'movies', :action => 'user_queue', :user_id => 2 %> |                                  
            <% elsif current_user.id == 2 %>
               <%= link_to 'Rob Queue', :controller => 'movies', :action => 'user_queue', :user_id => 1 %> |               
            <% end %>            
              <%= link_to 'My Queue', :controller => 'movies', :action => 'user_queue', :user_id => current_user.id %> |               
          <% end %>     
          
<%= link_to 'Tagged', tagged_movies_path %> |
<%= link_to 'Wanted', wanted_movies_path %> |
<%= link_to 'Rob\'s Faves', rob_movies_path %> |
<%= link_to 'Marina\'s Faves', marina_movies_path %> |
<%= link_to 'Recently Added', recent_added_movies_path %> |
<%= link_to 'Recently Watched', recent_watched_movies_path %> |
          <% if signed_in? %>
          <%= link_to 'New Movie', new_movie_path %> |
           <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>   (<%= current_user.email %>)
          <% else %>
            <%= link_to "Sign in", new_user_session_path %>
          <% end %> 
<br /><br />
<b>Slow: </b>
<%= link_to 'Unwatched', unwatched_movies_path %> |   
<%= link_to 'Watched', watched_movies_path %> |        
<%= link_to 'All', all_movies_path %> 
<br /><br />
<span id = "search_box">
 <%= form_tag({:controller=>"movies", :action=>"search"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search All Movies', name: nil %>
<% end %>
</span>

<div id="container">
  <table cellpadding="0" cellspacing="0" border="0" class="display" id="movie-table">
  <thead>
  <tr>   
    <th></th>
    <th style="display:none;"></th>
    <th>Name</th>
    <th>Length</th>    
    <th>Rating</th>
    <th>Year</th>
    <th>Description</th>
    <% if signed_in? and (current_user.id == 1 or current_user.id == 2) %>    
      <% if @show_watched %>
      <th>Seen</th>
      <% end %>
      <% if @show_tagged %>
      <th>Tagged</th>
      <% end %>
      <% if @show_wanted %>
      <th>Wanted</th>
      <% end %>
      <% if signed_in? and current_user.id == 1 and @show_rob %>        
        <th>Rob</th>
      <% end %>
      <% if signed_in? and current_user.id == 2 and @show_marina %>    
        <th>Marina</th>    
      <% end %>
    <% end %>
    <!--<th></th>
    <th></th>
    <th></th>-->
  </tr>
  </thead>
<% @movies.each do |movie| %>
  <tr id="<%= movie.id %>">
    <td>
      <% if !movie.poster_path.nil? %>
     <!-- <a href="http://www.themoviedb.org/movie/<%= movie.tmdb_id %>" target="_blank">-->
      <img class="magnify" data-magnifyby="6" src="http://d3gtl9l2a4fn1j.cloudfront.net/t/p/w185<%= movie.poster_path %>" width="61" height="88"  />
      <!--</a>-->
      <% else %>
       
      <% end %>
    </td>
    <td style="display:none;"><%= movie.name %></td>
    <td><!--<a href="http://www.imdb.com/title/<%= movie.imdb_id %>" target="_blank">-->
    <%= link_to movie.name, movie,:action => 'show', :id => @movie, :target => "_blank" %><!--</a>-->
        <p>
          <a href="<%= movie.wikipedia %>" target="_blank"><%= image_tag("wikipedia.png") %></a>
          <a href="http://www.imdb.com/title/<%= movie.imdb_id %>" target="_blank"><%= image_tag("imdb.png") %></a>
          <p>
            <a href="http://www.themoviedb.org/movie/<%= movie.tmdb_id %>" target="_blank"><%= image_tag("tmdb.png", :width => 16, :height => 16) %></a>          
            <% if movie.trailer %>
              <a href="http://www.youtube.com/watch?v=<%= movie.trailer %>" target="_blank"><%= image_tag("youtube.png") %></a>
            <% end %>
          </p>
        </p>   
    </td>
    <td><%if movie.runtime %> <b><%= "%03d" % movie.runtime %></b> <% end %> </td>
    <td><b><%= movie.rating %></b></td>
    <td><%= movie.year %></td>
    <td><%= movie.description %></td>
    <% if signed_in? and (current_user.id == 1 or current_user.id == 2) %>        
      <% if @show_watched %>
      <td>
      <% if signed_in? and current_user.id == 1 %>
      <%= link_to bool_link_text(movie.watched), toggle_watch_movie_path(movie), :remote => true, :id => "watch_link_#{movie.id}" %>
      <% else %>
        <%=  bool_link_text(movie.watched) %>
      <% end %>
      </td>
      <% end %>
      <% if @show_tagged %>      
      <td>
      <% if signed_in? and (current_user.id == 1 or current_user.id == 2) %>    
        <%= link_to bool_link_text(movie.is_tagged(current_user)), toggle_tag_movie_path(movie), :remote => true, :id => "tag_link_#{movie.id}" %>
      <% end %>
      </td>    
      <% end %>
      <% if signed_in? and @show_wanted and (current_user.id == 1 or current_user.id == 2) %>          
      <td>
        <%= link_to bool_link_text(movie.is_wanted(current_user)), toggle_want_movie_path(movie), :remote => true, :id => "want_link_#{movie.id}" %>
      </td>          
      <% end %>
      <% if signed_in? and current_user.id == 1 and @show_rob %>        
        <td>
          <%= link_to bool_link_text(movie.is_rob_favorite), toggle_rob_movie_path(movie), :remote => true, :id => "rob_link_#{movie.id}" %>
        </td>
      <% end %>      
      <% if signed_in? and current_user.id == 2 and @show_marina %>      
        <td>
          <%= link_to bool_link_text(movie.is_marina_favorite), toggle_marina_movie_path(movie), :remote => true, :id => "marina_link_#{movie.id}" %>
        <% end %>
        </td>       
    <% end %>
  </tr>
<% end %>
</table>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= form_for :movie, url: movies_path do |f| %>
  <% if @movie.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@movie.errors.count, "error") %> prohibited
      this movie from being saved:</h2>
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>or</p>
 
  <p>
    <%= f.label :tmdb_id %><br>
    <%= f.text_field:tmdb_id %>
  </p>
  
  <hr />
  
   
  <p>
    <%= f.label :watched %>  <%= f.check_box:watched %>
  </p>
  
    
  <p>
    <%= f.submit %>
  </p>
<% end %>  

<%= link_to 'Back', movies_path %>
  

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
      <% if !@movie.poster_path.nil? %>
      <img src="http://d3gtl9l2a4fn1j.cloudfront.net/t/p/w185<%= @movie.poster_path %>" />
      <% else %>
      <% end %>
</p

<a href="http://www.themoviedb.org/movie/<%= @movie.tmdb_id %>" target="_blank"><%= image_tag("tmdb.png", :width => 16, :height => 16) %></a>
<a href="http://www.imdb.com/title/<%= @movie.imdb_id %>" target="_blank"><%= image_tag("imdb.png") %></a>
<% if @movie.trailer %>
<a href="http://www.youtube.com/watch?v=<%= @movie.trailer %>" target="_blank"><%= image_tag("youtube.png") %></a>
<% end %>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Tmdb:</b>
  <%= @movie.tmdb_id %>
</p>

<p>
  <b>Runtime:</b>
  <%= @movie.runtime %>
</p>


<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Description:</b>
  <%= @movie.description %>
</p>

<%= link_to 'New', new_movie_path %> |
<!-- <%= link_to 'Edit', edit_movie_path(@movie) %> | -->
<%= link_to 'Back', movies_path %>

app/views/movies/toggle_marina.js.erb
$("#marina_link_<%= @movie.id %>").text("<%= bool_link_text(@movie.is_marina_favorite) %>");  
$("#movie_<%= @movie.id %>").effect("highlight"); 

app/views/movies/toggle_rob.js.erb
$("#rob_link_<%= @movie.id %>").text("<%= bool_link_text(@movie.is_rob_favorite) %>");  
$("#movie_<%= @movie.id %>").effect("highlight"); 

app/views/movies/toggle_tag.js.erb
$("#tag_link_<%= @movie.id %>").text("<%= bool_link_text(@movie.is_tagged(current_user)) %>");
$("#movie_<%= @movie.id %>").effect("highlight"); 

app/views/movies/toggle_want.js.erb
$("#want_link_<%= @movie.id %>").text("<%= bool_link_text(@movie.is_wanted(current_user)) %>");  
$("#movie_<%= @movie.id %>").effect("highlight"); 

app/views/movies/toggle_watch.js.erb
$("#watch_link_<%= @movie.id %>").text("<%= bool_link_text(@movie.watched) %>");  
$("#movie_<%= @movie.id %>").effect("highlight"); 